version: '3.9'
services:
  db:
    image: postgres:14.4
    environment:
      POSTGRES_DB: "pied_piper"
      POSTGRES_USER: "pied_piper"
      POSTGRES_PASSWORD: "pied_piper"
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:80"
