version: '3.9'
services:
  db:
    image: postgres:14.4
    environment:
      POSTGRES_DB: "pied_piper"
      POSTGRES_USER: "pied_piper"
      POSTGRES_PASSWORD: "pied_piper"
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: unless-stopped
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@team.cupsoft.ru"
  #     PGADMIN_DEFAULT_PASSWORD: "pied_piper"
  #     PGADMIN_LISTEN_PORT: "5050"
  #   volumes:
  #      - ./postgres-pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "5050:5050"

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:80"

  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - api
    depends_on:
      - api
    ports:
      - "3000:3000"
